    const placePage = async (nm) => { await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); const r = page.locator('.loc-row').filter({ hasText: new RegExp('^' + nm) }).first(); if (!(await r.count())) { console.log('   NO PLACE ROW', nm); return false; } await r.click(); await page.waitForTimeout(900); return true; };
    const sheetRows = async () => page.evaluate(() => { const s = [...document.querySelectorAll('.sheet')].pop(); return s ? [...s.querySelectorAll('.wl-row')].map(r => r.innerText.replace(/\s+/g, ' ')).join(' | ') : '(no sheet)'; });
    const fromSaid = async () => page.evaluate(() => { const t = document.querySelector('.in-list').innerText; const m = t.split(/FROM WHAT YOU SAID/i)[1]; return m ? m.split(/RECENT|ALL YOUR/i)[0].replace(/\n+/g, ' / ').trim() : '(none)'; });
    await grant();
    console.log('\n######## G part-of-name / longer name');
    const now = Date.now(); const PL = (id, nm) => ({ id, kind: 'place', owner: 'margaret', by: 'margaret', private: false, name: nm, order: now, createdAt: now, parent: null, photos: [] });
    await page.evaluate((s) => window.__rig.seed(s), [PL('pD', 'Desk'), PL('pG', 'Garage')]); await page.reload(); await page.waitForTimeout(800); await page.evaluate(() => window.__rig.rules(true));
    await logStart('egg timer', 'real_spoon.jpg');
    for (const w of ['in the garage cupboard', 'in the desk drawer', 'on the desk', 'in the garage', 'in the wooden crate', 'in the yearbook', 'in the plant sensor box', 'in the tin', 'in the kitchen', 'in the hall', 'on the shelf', 'in the box']) { await setWords(w); await openIn(); console.log(`WORDS ${JSON.stringify(w)} FROM-SAID: ${await fromSaid()} | NEW=${JSON.stringify(await newRows())}`); if (w === 'in the desk drawer') await shot('g-desk-drawer'); await cancelChoose(); }
    await leaveCam();
    console.log('\n######## I Move all from Crawl space');
    await placePage('Crawl space'); const ma = page.locator('.pl-all'); console.log('   move-all', await ma.count()); if (await ma.count()) { await ma.click(); await page.waitForTimeout(800); const rows = await sheetRows(); console.log('   ROWS:', rows); console.log('   offers Crawl space?', /Crawl space/.test(rows.replace(/in the Crawl space/g, '')), 'Memorabilia?', /^Memorabilia box|\| Memorabilia box/.test(rows), 'Wooden?', /Wooden box/.test(rows)); await srch('memorabilia'); await srch('wooden'); await srch('crawl'); await shot('i-moveall'); await cancelChoose(); await page.keyboard.press('Escape'); }
    console.log('-- I Move all from Garage (holds tool drawer etc, old data text)'); await placePage('Garage'); const ma2 = page.locator('.pl-all'); if (await ma2.count()) { await ma2.click(); await page.waitForTimeout(800); const rows = await sheetRows(); console.log('   ROWS:', rows.slice(0, 600)); await srch('tin'); await srch('garage'); await cancelChoose(); await page.keyboard.press('Escape'); }
    console.log('\n######## D Robert');
    await asUser('robert');
    await moveIt('wallet'); await openIn(); await pickIn('Kitchen counter'); await press('.lc-k.sv'); await page.waitForTimeout(900); const t1 = (await bodyText()).replace(/\s+/g, ' '); console.log('   MOVE note:', t1.slice(0, 260), '| undo', await undoCount()); await shot('d-robert-move'); await raw('wallet');
    await logStart('hammer', 'tooldrawer.jpg'); await openIn(); await pickIn('Garage shelf'); await press('.lc-k.sv'); await page.waitForTimeout(800); console.log('   LOG undo buttons:', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); await shot('d-robert-log');
    for (const p of ['White cardboard box', 'Pantry shelf']) { await placePage(p); const rm = page.locator('button:has-text("Remove this place")'); console.log(`   ${p}: remove shown=${await rm.count()}`, (await bodyText()).replace(/\s+/g, ' ').slice(0, 220)); }
    await shot('d-robert-place');
    await asUser('margaret');
    for (const p of ['White cardboard box']) { await placePage(p); const rm = page.locator('button:has-text("Remove this place")'); console.log(`   margaret ${p}: remove shown=${await rm.count()}`); }
    console.log('\n######## J small');
    await wid('tape measure'); await widPick(); await pickIn('Wooden box'); await page.locator('button.guess').filter({ hasText: /^Kitchen counter$/ }).first().click().catch(() => console.log('   no guess')); await page.waitForTimeout(400); await page.evaluate(() => window.scrollTo(0, 9999)); await shot('j-wid-summary'); console.log('   WID:', (await bodyText()).replace(/\s+/g, ' ').slice(-220)); await wsave(); await raw('tape measure');
    await wid('chisel'); await widPick(); console.log('   TITLE:', (await sheetText()).slice(0, 60)); await page.keyboard.press('Escape'); await page.waitForTimeout(300);
    await page.setViewportSize({ width: 390, height: 844 }); await wid('glue'); await page.evaluate(() => window.scrollTo(0, 9999)); const ov = await page.evaluate(() => [...document.querySelectorAll('button')].filter(b => /No place yet/.test(b.innerText)).map(b => `${b.scrollWidth}>${b.clientWidth} right=${Math.round(b.getBoundingClientRect().right)}`)); console.log('   No place yet overflow:', ov); await shot('j-noplace'); await page.click('button.back').catch(() => {}); { const lv = page.locator('button:has-text("Leave")'); if (await lv.count()) await lv.first().click(); }
    await home(); await page.click(LOG); await page.waitForTimeout(900); AI = { name: 'wallet' }; SAME = { index: 1, sure: true }; await cam('wallet.jpg'); await tap('.lc-shutter', { wait: 2500 }); SAME = { index: -1, sure: false }; console.log('   CAM before', await camText()); await btn(/^Yes$/); console.log('   CAM after Yes', await camText()); await shot('j-wallet-yes'); await leaveCam();
    console.log('   ', errs());
