    const noAuto = () => page.evaluate(() => { window.__noAuto = true; });
    const H = (s) => page.evaluate((s) => [...document.querySelectorAll(s)].map(e => e.outerHTML.replace(/src="data:[^"]*"/g, 'src=""')).join('\n').slice(0, 2500), s);
    await noAuto();
    await openItem('baseball card'); await noAuto();
    await tap('button:has-text("Move it")', { wait: 1000 });
    console.log('SHUTTER0', await H('.lc-shutter'));
    console.log('SQ0', await H('.lv-sq'));
    WHERE.length = 0; WHERE.push({ name: 'kitchen counter', known: 'Kitchen counter', sure: true }, { name: 'x' }, { name: 'y' }, { name: 'z' });
    await cam('real_desk.jpg'); await shutter(); await page.waitForTimeout(800);
    console.log('reqs', reqTimes.join(','));
    await press('.pf-same'); await page.waitForTimeout(1500);
    await ui('after another'); await shot('f3-after-another');
    console.log('SHUTTER1', await H('.lc-shutter'));
    console.log('SQ1', await H('.lv-sq'));
    await cam('closet.jpg'); await shutter(); await page.waitForTimeout(1500);
    console.log('reqs', reqTimes.join(','));
    await ui('after 2nd shot'); await shot('f3-after-2nd');
    await sel(1); await page.waitForTimeout(500);
    await ui('after tap L1'); await shot('f3-after-tapL1');
    console.log('SHUTTER2', await H('.lc-shutter'));
