    await page.evaluate(() => window.__rig.rules(true));
    const wid = async (name) => { await home(); await page.click(LOG); await page.waitForTimeout(1000); await btn(/Type it instead/); await page.waitForTimeout(500); await page.locator('input.place-input').first().fill(name); await page.waitForTimeout(200); };
    const pick = async () => { await page.click('button.path.in'); await page.waitForTimeout(800); };
    const srchW = async (q) => { const i = page.locator('.sheet input, .in-list input').last(); await i.fill(''); await i.type(q, { delay: 10 }); await page.waitForTimeout(500); console.log(`SEARCH ${JSON.stringify(q)} -> ${(await sheetText()).slice(0, 260)}`); };
    const wsave = async () => { await page.locator('button:has-text("Save")').last().click(); await page.waitForTimeout(1800); };
    console.log('\n######## W4 Somewhere else typed'); await wid('drill'); await page.locator('button').filter({ hasText: /^Somewhere else$/ }).first().click(); await page.waitForTimeout(600);
    await page.locator('input.place-input').nth(1).fill('in the shoebox under the bed'); await page.waitForTimeout(600); await page.evaluate(() => window.scrollTo(0, 9999)); await shot('w4-typed'); console.log('PAGE', (await bodyText()).replace(/\s+/g, ' ').slice(-200)); await wsave(); await dumpItem('drill'); await allPlaces();
    console.log('\n######## W4b Somewhere else typed = existing place name'); await wid('saw'); await page.locator('button').filter({ hasText: /^Somewhere else$/ }).first().click(); await page.waitForTimeout(600);
    await page.locator('input.place-input').nth(1).fill('pantry SHELF'); await page.waitForTimeout(600); await wsave(); await dumpItem('saw');
    await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); console.log('PLACES PAGE after W4', (await bodyText()).replace(/\s+/g, ' ')); await shot('w4-places');
    await logStart('pliers', 'tooldrawer.jpg'); await openIn(); console.log('IN LIST after W4:', (await inText()).slice(0, 700)); await shot('w4-inlist'); await cancelChoose(); await press('.lc-x'); await page.waitForTimeout(300); { const lv = page.locator('button:has-text("Leave")'); if (await lv.count()) await lv.first().click(); }
    console.log('\n######## W6b WID: pick Wooden box then guess Kitchen counter -> summary'); await wid('tape measure'); await pick(); await pickIn('Wooden box'); await page.locator('button.guess').filter({ hasText: /^Kitchen counter$/ }).first().click(); await page.waitForTimeout(400); await page.evaluate(() => window.scrollTo(0, 9999)); await page.waitForTimeout(300); await shot('w6-bottom'); console.log('BOTTOM', (await bodyText()).replace(/\s+/g, ' ').slice(-120)); await page.click('button.back'); await page.waitForTimeout(500); { const lv = page.locator('button:has-text("Leave")'); if (await lv.count()) await lv.first().click(); }
    console.log('\n######## W9 WID "Attic" new place (no place doc?) then ☰ Places'); await wid('fan'); await pick(); await srchW('Attic'); await page.locator('button').filter({ hasText: /New place: Attic/ }).first().click(); await page.waitForTimeout(700); await wsave(); await allPlaces();
    await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); console.log('PLACES PAGE', (await bodyText()).replace(/\s+/g, ' ')); await shot('w9-places');
    console.log('-- camera: words "in the attic"'); await logStart('heater', 'closet.jpg'); await setWords('in the attic'); await openIn(); console.log((await inText()).slice(0, 200)); await cancelChoose(); await press('.lc-x'); await page.waitForTimeout(300); { const lv = page.locator('button:has-text("Leave")'); if (await lv.count()) await lv.first().click(); }
    console.log('\n######## W10 WID pass: hunter2'); await wid('router'); await pick(); await srchW('pass: hunter2'); await shot('w10');
    console.log('\n######## W11 "Attic   room" place made by camera, then search "attic room"'); await logStart('fan2', 'closet.jpg'); await openIn(); await page.locator('.in-list .wl-search input').type('attic   room', { delay: 10 }); await page.waitForTimeout(400); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(500); await doSave(); await allPlaces();
    await logStart('fan3', 'closet.jpg'); await openIn(); await page.locator('.in-list .wl-search input').type('attic room', { delay: 10 }); await page.waitForTimeout(400); console.log('SEARCH attic room ->', (await inText()).slice(0, 200)); await setWords(''); await cancelChoose(); await setWords('in the attic room'); await openIn(); console.log('WORDS ->', (await inText()).slice(0, 200)); await shot('w11');
