    await page.evaluate(() => window.__rig.rules(true));
    const moveIt = async (nm) => { await openItem(nm); await tap('button:has-text("Move it")', { wait: 1200 }); };
    const undo = async (label) => { const u = page.locator('button:has-text("Undo")').filter({ visible: true }).first(); if (!(await u.count())) { console.log('   NO UNDO VISIBLE', label || ''); return false; } await u.click(); await page.waitForTimeout(1500); console.log('   UNDONE ->', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); return true; };
    const cnt = async () => { const d = await D(); const k = {}; d.forEach(x => { const key = x.kind + (x.deleted ? '-del' : '') + (x.kind === 'edge' && x.until ? '-ended' : ''); k[key] = (k[key] || 0) + 1; }); return JSON.stringify(k); };
    const snapsOf = async (nm) => { const d = await D(); const it = d.find(x => x.kind === 'item' && x.name === nm && !x.deleted); if (!it) return console.log('   no', nm); const s = d.filter(x => x.kind === 'snap' && x.itemId === it.id); console.log(`   ${nm}: cover=${(it.photo||'').slice(-16)} photoCount=${it.photoCount} lastSeen=${it.lastSeenAt} snaps=${JSON.stringify(s.map(z => ({ id: z.id, tail: (z.photo||'').slice(-12), del: z.deleted || false })))}`); };
    console.log('\n######## U1 Log with a New place, Home card Undo'); console.log('COUNTS', await cnt()); await allPlaces();
    await logStart('egg timer', 'real_spoon.jpg'); await setWords('in the garden shed'); await openIn(); const nr = page.locator('.in-list button').filter({ hasText: /New place/ }).first(); console.log('NEW', await nr.innerText().catch(() => 'none')); await nr.click(); await page.waitForTimeout(500); await doSave(); await shot('u1-home-card'); console.log('COUNTS', await cnt()); await allPlaces();
    await undo('home card'); await shot('u1-undone'); console.log('COUNTS', await cnt()); await allPlaces(); await dumpItem('egg timer');
    console.log('\n######## U2 Move it with New place, item page Undo');
    await moveIt('baseball card'); await setWords('in the cedar chest'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(500); await doSave(); await allPlaces(); await undo('item page'); await allPlaces(); await dumpItem('baseball card');
    console.log('\n######## U3 Words dated, then Move (no words), Undo -> words date kept?');
    await moveIt('yearbook 1978'); await setWords('bottom of the box, under the photos'); await doSave(); await page.waitForTimeout(61000);
    await moveIt('yearbook 1978'); await openIn(); await pickIn('Pantry shelf'); await doSave(); await undo('item page'); await shot('u3-undone'); const it3 = await dumpItem('yearbook 1978'); console.log('   PAGE', (await bodyText()).replace(/\s+/g, ' ').slice(0, 220));
    console.log('\n######## U4 re-log a known item: Your wallet? Yes, new photo + words + In, Home card Undo');
    await snapsOf('wallet'); await dumpItem('wallet');
    await home(); await page.click(LOG); await page.waitForTimeout(900); AI = { name: 'wallet' }; SAME = { index: 1, sure: true }; await cam('wallet.jpg'); await tap('.lc-shutter', { wait: 2500 }); SAME = { index: -1, sure: false }; console.log('   ask?', /Your wallet\?/.test(await camText()));
    await btn(/^Yes$/); console.log('   CAM', await camText()); await setWords('in my coat pocket'); await openIn(); await pickIn('Linen closet'); await doSave(); await shot('u4-card'); await snapsOf('wallet'); await dumpItem('wallet');
    await undo('home card wallet'); await shot('u4-undone'); await snapsOf('wallet'); await dumpItem('wallet'); console.log('COUNTS', await cnt());
    await itemPage('wallet', 'u4-wallet-page');
    console.log('\n######## U5 double Undo (tap Undo twice quickly)');
    await moveIt('baseball card'); await openIn(); await pickIn('Garage shelf'); await doSave(); const u = page.locator('button:has-text("Undo")').filter({ visible: true }).first(); if (await u.count()) { await u.click(); await u.click({ timeout: 800 }).catch(() => console.log('   second tap: gone')); await page.waitForTimeout(1500); } await dumpItem('baseball card'); await placeEdges();
    console.log('\n######## O1 old data: reading glasses (Hall table text, no link) Move it, words only');
    await moveIt('reading glasses'); console.log('   CAM', await camText(), 'save', await saveState()); await shot('o1-move-open'); await setWords('on the left side, by the keys'); await doSave(); await dumpItem('reading glasses'); await itemPage('reading glasses', 'o1-page');
    console.log('\n######## O2 old data: wallet Put it in? (Hall table text)');
    await openItem('wallet'); console.log('   put-it-in btn?', await page.locator('button:has-text("Put it in a place or a box")').count()); console.log('   PAGE', (await bodyText()).replace(/\s+/g, ' ').slice(0, 260)); await shot('o2-wallet');
    console.log('\n######## O3 old data: tool drawer (box at Garage text) Move it -> x -> Save');
    await moveIt('tool drawer'); console.log('   CAM', await camText(), 'save', await saveState()); await page.locator('.w1-in .x').first().click().catch(() => console.log('   no x')); await page.waitForTimeout(400); console.log('   save after x', await saveState()); await doSave(); await dumpItem('tool drawer'); await undo('tool drawer'); await dumpItem('tool drawer');
    console.log('\n######## O4 old data: coffee can (no location) words; tin box old data Put in');
    await openItem('tin box'); console.log('   PAGE', (await bodyText()).replace(/\s+/g, ' ').slice(0, 260));
