    const moveIt = async (nm) => { await openItem(nm); await tap('button:has-text("Move it")', { wait: 1200 }); };
    const asUser = async (uid) => { await page.evaluate((u) => { localStorage.setItem('rig-uid', u); const p = JSON.parse(localStorage.getItem('recall-prefs') || '{}'); p.whose = u === 'robert' ? 'margaret' : null; localStorage.setItem('recall-prefs', JSON.stringify(p)); }, uid); await page.reload(); await page.waitForSelector('.screen'); await page.waitForTimeout(800); await page.evaluate(() => window.__rig.rules(true)); console.log('   now user', uid); };
    const undo = async (label) => { const u = page.locator('button:has-text("Undo")').filter({ visible: true }).first(); if (!(await u.count())) { console.log('   NO UNDO VISIBLE', label || ''); return false; } await u.click(); await page.waitForTimeout(1500); console.log('   UNDONE ->', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); return true; };
    const errs = () => `pageErr=${errors.length} consoleErr=${consoleErrors.length}${consoleErrors.length ? ' last=' + String(consoleErrors[consoleErrors.length - 1]).slice(0, 120) : ''}`;
    const placePage = async (nm) => { await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); const r = page.locator('.loc-row').filter({ hasText: new RegExp('^' + nm) }).first(); if (!(await r.count())) { console.log('   NO PLACE ROW', nm); return false; } await r.click(); await page.waitForTimeout(900); return true; };
    const pickR = async (nm) => { const l = page.locator('.sheet .wl-row').filter({ has: page.locator(`b:text-is("${nm}")`) }).last(); if (!(await l.count())) { console.log('   NOT OFFERED:', nm); return false; } await l.scrollIntoViewIfNeeded(); await l.click(); await page.waitForTimeout(1200); console.log('   picked', nm); return true; };
    const PP = async () => console.log('   PAGE:', (await bodyText()).replace(/\s+/g, ' ').replace(/^.*?Where this place is/, 'Where:').slice(0, 260));
    await page.evaluate((s) => window.__rig.seed(s, 'recall_grants'), [{ id: 'margaret_robert', grantor: 'margaret', grantee: 'robert', role: 'editor', createdAt: Date.now() - 86400000 }]);
    await page.evaluate(() => window.__rig.rules(true));
    console.log('\n######## M: Margaret says words on egg timer'); await logStart('egg timer', 'real_spoon.jpg'); await setWords('under the stairs'); await doSave(); await dumpItem('egg timer');
    await asUser('robert');
    console.log('\n######## R1 Robert: Put it in on Margaret\'s egg timer, then Undo'); await openItem('egg timer'); await tap('button:has-text("Put it in a place or a box")', { wait: 1000 }); await pickIn('Pantry shelf'); console.log('   ', errs()); await dumpItem('egg timer'); await undo('toast'); await dumpItem('egg timer'); await itemPage('egg timer', 'r1-robert-after-undo'); console.log('   ', errs());
    console.log('\n######## R2 Robert: Move it on baseball card with words + New place; Undo'); await moveIt('baseball card'); await setWords('in the cedar chest'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click().catch(() => console.log('   no new')); await page.waitForTimeout(500); await doSave(); console.log('   ', errs()); await dumpItem('baseball card'); await allPlaces(); await undo('item page'); await dumpItem('baseball card'); console.log('   ', errs());
    console.log('\n######## R3 Robert: Log new item with New place; Home Undo'); await logStart('hammer', 'tooldrawer.jpg'); await setWords('in the workshop'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click().catch(() => {}); await page.waitForTimeout(500); await doSave(); console.log('   ', errs()); await dumpItem('hammer'); await allPlaces(); await undo('home'); await dumpItem('hammer'); await allPlaces();
    console.log('\n######## R4 Robert: Write it down -> pick Wooden box'); await home(); await page.click(LOG); await page.waitForTimeout(900); await btn(/Type it instead/); await page.locator('input.place-input').first().fill('chisel'); await page.click('button.path.in'); await page.waitForTimeout(800); await pickIn('Wooden box'); await page.locator('button:has-text("Save")').last().click(); await page.waitForTimeout(1800); console.log('   ', errs()); await dumpItem('chisel');
    console.log('\n######## R5 Robert: place page Desk drawer (holds Margaret\'s PRIVATE passport)'); await placePage('Desk drawer'); await PP(); await shot('r5-robert-desk');
    const ma = page.locator('.pl-all'); console.log('   move-all', await ma.count()); if (await ma.count()) { await ma.click(); await page.waitForTimeout(800); await pickR('Kitchen counter'); await PP(); console.log('   ', errs()); }
    else { await page.locator('.pl-move').first().click().catch(() => {}); await page.waitForTimeout(800); await pickR('Kitchen counter'); await PP(); console.log('   ', errs()); }
    await dumpItem('passport'); await dumpItem('3D model of plant sensor');
    const rm = page.locator('button:has-text("Remove this place")'); console.log('   remove disabled (robert)?', await rm.isDisabled().catch(() => 'n/a'));
    console.log('\n######## R6 Robert: Where this place is (Margaret\'s Pantry shelf -> Garage shelf), then Not in anything'); await placePage('Pantry shelf'); await page.click('.pl-where'); await page.waitForTimeout(800); await pickR('Garage shelf'); await PP(); console.log('   ', errs()); await placeEdges();
    await page.click('.pl-where'); await page.waitForTimeout(800); await page.locator('.sheet button').filter({ hasText: /Not in anything/ }).first().click().catch(() => console.log('   no NIA')); await page.waitForTimeout(900); await PP(); console.log('   ', errs()); await placeEdges();
    console.log('\n######## R7 Robert: Remove Margaret\'s empty place Linen closet'); await placePage('Linen closet'); const rm2 = page.locator('button:has-text("Remove this place")'); console.log('   disabled?', await rm2.isDisabled().catch(() => 'n/a')); if (!(await rm2.isDisabled().catch(() => true))) { await rm2.click(); await page.waitForTimeout(600); await page.locator('button').filter({ hasText: /^Remove$/ }).last().click().catch(() => {}); await page.waitForTimeout(1200); console.log('   after:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 160)); } console.log('   ', errs()); await allPlaces();
    console.log('\n######## R8 Robert: Move it on Margaret\'s reading glasses (old data) words only'); await moveIt('reading glasses'); await setWords('on the hall table, left side'); await doSave(); console.log('   ', errs()); await dumpItem('reading glasses');
    await asUser('margaret'); await itemPage('egg timer', 'r9-margaret-egg'); await itemPage('baseball card', 'r9-margaret-card'); await itemPage('reading glasses', 'r9-margaret-glasses');
    console.log('   PASSPORT seen by margaret:'); await dumpItem('passport');
