    const moveIt = async (nm) => { await openItem(nm); await tap('button:has-text("Move it")', { wait: 1200 }); };
    const asUser = async (uid) => { await page.evaluate((u) => { localStorage.setItem('rig-uid', u); const p = JSON.parse(localStorage.getItem('recall-prefs') || '{}'); p.whose = u === 'robert' ? 'margaret' : null; localStorage.setItem('recall-prefs', JSON.stringify(p)); }, uid); await page.reload(); await page.waitForSelector('.screen'); await page.waitForTimeout(800); await page.evaluate(() => window.__rig.rules(true)); console.log('   now user', uid); };
    const undoCount = async () => page.locator('button:has-text("Undo")').filter({ visible: true }).count();
    const undo = async (label) => { const u = page.locator('button:has-text("Undo")').filter({ visible: true }).first(); if (!(await u.count())) { console.log('   NO UNDO VISIBLE', label || ''); return false; } await u.click(); await page.waitForTimeout(1500); console.log('   UNDONE'); return true; };
    await page.evaluate((s) => window.__rig.seed(s, 'recall_grants'), [{ id: 'margaret_robert', grantor: 'margaret', grantee: 'robert', role: 'editor', createdAt: Date.now() - 86400000 }]);
    await page.evaluate(() => window.__rig.rules(true));
    console.log('\n######## A Margaret: baseball card Move it -> x only -> Save -> Undo?');
    await moveIt('baseball card'); await page.locator('.w1-in .x').first().click(); await page.waitForTimeout(400); await press('.lc-k.sv'); await page.waitForTimeout(600); await shot('a-x-saved'); console.log('   undo buttons:', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 220)); await undo('x-only'); await dumpItem('baseball card');
    console.log('\n######## B Robert words on yearbook; Margaret moves it (no words) and Undoes -> who said?');
    await asUser('robert'); await moveIt('yearbook 1978'); await setWords('bottom of the box, under the photos'); await doSave();
    await asUser('margaret'); await moveIt('yearbook 1978'); await openIn(); await pickIn('Pantry shelf'); await doSave(); await undo('margaret move'); await shot('b-after-undo'); await dumpItem('yearbook 1978'); await itemPage('yearbook 1978', 'b-page');
    console.log('\n######## C Robert: Put it in / Move it / Log -> is Undo shown?');
    await logStart('egg timer', 'real_spoon.jpg'); await setWords('under the stairs'); await doSave();
    await asUser('robert');
    await openItem('egg timer'); await tap('button:has-text("Put it in a place or a box")', { wait: 1000 }); await pickIn('Pantry shelf'); await page.waitForTimeout(100); console.log('   put-in undo buttons:', await undoCount()); await shot('c-robert-putin');
    await moveIt('egg timer'); await openIn(); await pickIn('Kitchen counter'); await press('.lc-k.sv'); await page.waitForTimeout(800); console.log('   move undo buttons:', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); await shot('c-robert-move');
    await logStart('hammer', 'tooldrawer.jpg'); await openIn(); await pickIn('Garage shelf'); await press('.lc-k.sv'); await page.waitForTimeout(800); console.log('   log undo buttons:', await undoCount()); await shot('c-robert-log');
    console.log('\n######## D Robert: Remove empty place');
    await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); await page.locator('.loc-row').filter({ hasText: /^White cardboard box/ }).first().click(); await page.waitForTimeout(900);
    await page.locator('button:has-text("Remove this place")').click(); await page.waitForTimeout(600); await page.locator('button').filter({ hasText: /^Remove$/ }).last().click(); await page.waitForTimeout(1500); await shot('d-robert-remove'); console.log('   after:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200), '| pageErrors', errors.length); await allPlaces();
