    const moveIt = async (nm) => { await openItem(nm); await tap('button:has-text("Move it")', { wait: 1200 }); };
    const undo = async () => { const u = page.locator('button.u').first(); if (!(await u.count())) { console.log('   NO UNDO'); return; } await u.click(); await page.waitForTimeout(1500); console.log('   UNDONE ->', (await bodyText()).replace(/\s+/g, ' ').slice(0, 300)); };
    console.log('\n######## M4+Undo: words, then move to Kitchen counter, Undo');
    await fresh2(); await moveIt('baseball card'); await words('top tray, in the plastic sleeve'); await doSave();
    await moveIt('baseball card'); await openIn(); await pickIn('Kitchen counter'); await doSave();
    await undo(); await shot('m4-undone'); await dumpItem('baseball card'); await placeEdges();
    console.log('\n######## M5 photo only + Undo');
    await moveIt('baseball card'); AI = { name: 'baseball card' }; await cam('closet.jpg'); await tap('.lc-shutter', { wait: 1800 }); console.log('CAM:', await camText(), 'save', await saveState()); await shot('m5-after-photo');
    await doSave(); const a = await dumpItem('baseball card'); console.log('photos field', JSON.stringify(Object.keys(a)), (a.photos || []).length);
    await shot('m5-saved'); await undo(); const b = await dumpItem('baseball card'); console.log('after undo photos', (b.photos || []).length, b.photoCount);
    console.log('\n######## M10 type then erase words -> Save?');
    await moveIt('baseball card'); await words('abc'); console.log('save after abc', await saveState()); await setWords(''); console.log('save after erase', await saveState());
    await setWords('   '); console.log('save after spaces only', await saveState());
    await setWords('top tray, in the plastic sleeve'); console.log('save with SAME words as last time', await saveState());
    await setWords('');
    console.log('\n######## M11 pick another then pick original back');
    await openIn(); await pickIn('Pantry shelf'); console.log('save', await saveState()); await openIn(); console.log('SHEET', (await inText()).slice(0, 200)); await pickIn('Wooden box'); console.log('save after re-picking original', await saveState(), await camText());
    console.log('\n######## M12 x then pick original');
    await page.locator('.w1-in .x').first().click(); await page.waitForTimeout(500); console.log('after x', await camText(), 'save', await saveState()); await shot('m12-after-x');
    await openIn(); await pickIn('Wooden box'); console.log('after re-pick', await camText(), 'save', await saveState());
    console.log('\n######## M6 Cancel with changes');
    await words('in the hall closet'); await openIn(); await pickIn('Linen closet'); await press('.lc-x'); await page.waitForTimeout(1000); await ui('after cancel'); await shot('m6-cancel');
    await dumpItem('baseball card'); await allPlaces();
    console.log('\n######## M2 x only -> Save -> Not put away');
    await moveIt('baseball card'); await page.locator('.w1-in .x').first().click(); await page.waitForTimeout(500); console.log('save', await saveState()); await doSave(); await shot('m2-saved'); await ui('m2 page');
    await dumpItem('baseball card'); await notPut(); await shot('m2-home');
