    // ---- r (release 1) helpers ----
    const words = async (s) => { const i = page.locator('.w1-words input').first(); await i.click(); await page.keyboard.type(s, { delay: 15 }); await page.waitForTimeout(400); };
    const setWords = async (s) => { await page.locator('.w1-words input').first().fill(s); await page.waitForTimeout(400); };
    const openIn = async () => { const l = page.locator('.w1-in, .w1-chip, [class*="w1-"]:has-text("In:")').first(); await l.click(); await page.waitForTimeout(800); };
    const inText = async () => sheetText('.in-list');
    const pickIn = async (name) => { const l = page.locator('.in-list .wl-row').filter({ has: page.locator(`b:text-is("${name}")`) }).first(); if (!(await l.count())) { console.log('   pickIn: no row', name); return false; } await l.scrollIntoViewIfNeeded(); await l.click(); await page.waitForTimeout(700); console.log('   picked In', name); return true; };
    const camText = async () => page.evaluate(() => { const e = document.querySelector('.lc'); return e ? e.innerText.replace(/\n+/g, ' / ') : '(no camera)'; });
    const saveState = async () => page.evaluate(() => { const b = document.querySelector('.lc-k.sv'); return b ? (b.disabled ? 'OFF' : 'on') : '-'; });
    const doSave = async () => { console.log('   Save is', await saveState()); await press('.lc-k.sv'); await page.waitForTimeout(2000); console.log('   after save:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); };
    const D = () => page.evaluate(() => window.__rig.dump());
    const dumpItem = async (nm) => { const d = await D(); const it = d.find(x => x.kind === 'item' && !x.deleted && (x.name||'').toLowerCase() === nm.toLowerCase()); if (!it) { console.log('NO ITEM', nm); return null; }
      const e = d.filter(x => x.kind === 'edge' && x.from === it.id); const h = (it.history || []).map(x => { const y = { ...x }; for (const k in y) if (typeof y[k] === 'string' && y[k].length > 80) y[k] = y[k].slice(0, 60) + `…(${y[k].length})`; return y; });
      console.log(`ITEM ${nm}: id=${it.id} loc=${JSON.stringify(it.location)} photos=${it.photoCount}/${(it.photos||[]).length} needsPlace=${it.needsPlace} by=${it.by} owner=${it.owner}\n  history=${JSON.stringify(h)}\n  edges=${JSON.stringify(e.map(x => ({ to: x.to, until: x.until ? 'ENDED' : null, by: x.by })))}`); return it; };
    const allPlaces = async () => { const d = await D(); const p = d.filter(x => x.kind === 'place' && !x.deleted).map(x => x.name); const dup = p.filter((n, i) => p.findIndex(m => m.toLowerCase().trim() === n.toLowerCase().trim()) !== i); console.log(`PLACES(${p.length}): ${p.join(', ')}${dup.length ? '  DUPLICATES: ' + dup.join(',') : ''}`); return p; };
    const placeEdges = async () => { const d = await D(); const r = d.filter(x => x.kind === 'edge' && !x.until).map(x => { const f = d.find(z => z.id === x.from); return `${f ? f.name : x.from}->${x.to.name || x.to.id}`; }); console.log('LIVE EDGES:', r.join(' | ')); const multi = {}; for (const x of d.filter(x => x.kind === 'edge' && !x.until)) multi[x.from] = (multi[x.from] || 0) + 1; const m = Object.entries(multi).filter(([, n]) => n > 1); if (m.length) console.log('  !! MULTIPLE LIVE EDGES:', JSON.stringify(m)); };
    const notPut = async () => { await home(); const t = await page.locator('.notput').first().innerText().catch(() => '(no chip)'); console.log('   NOT PUT AWAY chip:', t); return t; };
    const itemPage = async (nm, label) => { await openItem(nm); const t = (await bodyText()).replace(/\n+/g, ' / '); const i = t.indexOf(nm.slice(0, 1).toUpperCase() + nm.slice(1)); console.log(`   ITEM PAGE ${nm}:`, t.slice(Math.max(0, t.lastIndexOf(' / Find item') ), 900)); if (label) await shot(label); return t; };
    const fresh2 = async () => { WHERE.length = 0; await seedHouse(); await page.evaluate(() => window.__rig.rules(true)); };
