    const moveIt = async (nm) => { await openItem(nm); await tap('button:has-text("Move it")', { wait: 1200 }); };
    const undo = async (sel = 'button.u') => { const u = page.locator(sel).filter({ visible: true }).first(); if (!(await u.count())) { console.log('   NO UNDO', sel); return false; } await u.click(); await page.waitForTimeout(1500); console.log('   UNDONE ->', (await bodyText()).replace(/\s+/g, ' ').slice(0, 250)); return true; };
    const snapsOf = async (nm) => { const d = await D(); const it = d.find(x => x.kind === 'item' && x.name === nm && !x.deleted); const s = d.filter(x => x.kind === 'snap' && x.itemId === it.id); console.log(`   ${nm}: cover=${(it.photo||'').slice(-24)} photoCount=${it.photoCount} snaps=${JSON.stringify(s.map(z => ({ id: z.id, tail: (z.photo||'').slice(-16), del: z.deleted || false })))}`); };
    console.log('\n######## FIX2 undo of Move with photo');
    await snapsOf('baseball card');
    await moveIt('baseball card'); AI = { name: 'baseball card' }; await cam('closet.jpg'); await tap('.lc-shutter', { wait: 1800 }); await doSave(); await snapsOf('baseball card'); await shot('fix2-saved');
    await undo(); await snapsOf('baseball card'); await dumpItem('baseball card'); await shot('fix2-undone');
    await page.reload(); await page.waitForTimeout(1200); await openItem('baseball card'); await shot('fix2-undone-reload'); console.log('PAGE', (await bodyText()).replace(/\s+/g, ' ').slice(0, 300));
    console.log('-- two photos + pick + words, then undo');
    await moveIt('baseball card'); AI = { name: 'baseball card' }; await cam('glasses.jpg'); await tap('.lc-shutter', { wait: 1800 }); await cam('keys.jpg'); await tap('.lc-shutter', { wait: 1800 }); await setWords('on the top shelf'); await openIn(); await pickIn('Pantry shelf'); await doSave(); await snapsOf('baseball card');
    await undo(); await snapsOf('baseball card'); await dumpItem('baseball card'); await placeEdges();
    console.log('\n######## FIX6 Put it in a place or a box');
    await logStart('egg timer', 'real_spoon.jpg'); await words('under the stairs'); await doSave(); await dumpItem('egg timer');
    await page.waitForTimeout(2500);
    await openItem('egg timer'); await shot('fix6-page-before');
    await tap('button:has-text("Put it in a place or a box")', { wait: 1200 }); await shot('fix6-sheet'); console.log('SHEET', (await sheetText()).slice(0, 300));
    await pickIn('Pantry shelf'); await page.waitForTimeout(300); await shot('fix6-toast'); console.log('AFTER PICK', (await bodyText()).replace(/\s+/g, ' ').slice(0, 400));
    await dumpItem('egg timer');
    await undo('button:has-text("Undo")'); await shot('fix6-undone'); await dumpItem('egg timer'); await placeEdges();
