    // ---- v3 helpers ----
    await page.evaluate(() => window.__rig.rules(true));
    const moveIt = async (nm) => { await openItem(nm); await tap('button:has-text("Move it")', { wait: 1200 }); };
    const asUser = async (uid) => { await page.evaluate((u) => { localStorage.setItem('rig-uid', u); const p = JSON.parse(localStorage.getItem('recall-prefs') || '{}'); p.whose = u === 'robert' ? 'margaret' : null; localStorage.setItem('recall-prefs', JSON.stringify(p)); }, uid); await page.reload(); await page.waitForSelector('.screen'); await page.waitForTimeout(800); await page.evaluate(() => window.__rig.rules(true)); console.log('   now user', uid); };
    const grant = async () => { await page.evaluate((s) => window.__rig.seed(s, 'recall_grants'), [{ id: 'margaret_robert', grantor: 'margaret', grantee: 'robert', role: 'editor', createdAt: Date.now() - 86400000 }]); await page.evaluate(() => window.__rig.rules(true)); };
    const undoCount = async () => page.locator('button:has-text("Undo")').filter({ visible: true }).count();
    const undo = async (label) => { const u = page.locator('button:has-text("Undo")').filter({ visible: true }).first(); if (!(await u.count())) { console.log('   NO UNDO VISIBLE', label || ''); return false; } await u.click(); await page.waitForTimeout(1500); console.log('   UNDONE', label || '', '->', (await bodyText()).replace(/\s+/g, ' ').slice(0, 160)); return true; };
    const errs = () => `pageErr=${errors.length} consoleErr=${consoleErrors.length}${consoleErrors.length ? ' last=' + String(consoleErrors[consoleErrors.length - 1]).slice(0, 160) : ''}${errors.length ? ' lastPE=' + String(errors[errors.length - 1]).slice(0, 160) : ''}`;
    const raw = async (nm) => { const d = await D(); const it = d.find(x => x.kind === 'item' && !x.deleted && (x.name||'').toLowerCase() === nm.toLowerCase()); if (!it) { console.log('RAW: NO ITEM', nm); return null; }
      const t = JSON.parse(JSON.stringify(it, (k, v) => typeof v === 'string' && v.length > 80 ? v.slice(0, 30) + `…(${v.length})` : v)); delete t.thumb; delete t.photo; console.log(`RAW ${nm}: ${JSON.stringify(t)}`);
      const e = d.filter(x => x.kind === 'edge' && x.from === it.id).map(x => `${x.to.name || x.to.id}${x.until ? '[ended]' : '[LIVE]'} by=${x.by} since=${x.since}`); console.log(`   edges: ${e.join(' | ') || 'none'}`); return it; };
    const cnt = async () => { const d = await D(); const k = {}; d.forEach(x => { const key = x.kind + (x.deleted ? '-del' : '') + (x.kind === 'edge' && x.until ? '-ended' : ''); k[key] = (k[key] || 0) + 1; }); return JSON.stringify(k); };
    const leaveCam = async () => { await press('.lc-x'); await page.waitForTimeout(500); const lv = page.locator('button:has-text("Leave")'); if (await lv.count()) await lv.first().click(); await page.waitForTimeout(300); };
    const wid = async (name) => { await home(); await page.click(LOG); await page.waitForTimeout(1000); await btn(/Type it instead/); await page.waitForTimeout(500); await page.locator('input.place-input').first().fill(name); await page.waitForTimeout(200); };
    const widPick = async () => { await page.click('button.path.in'); await page.waitForTimeout(800); };
    const widElse = async (txt) => { await page.locator('button').filter({ hasText: /^Somewhere else$/ }).first().click(); await page.waitForTimeout(600); await page.locator('input.place-input').nth(1).fill(txt); await page.waitForTimeout(600); };
    const srchW = async (q) => { const i = page.locator('.sheet input, .in-list input').last(); await i.fill(''); await i.type(q, { delay: 10 }); await page.waitForTimeout(500); console.log(`SEARCH ${JSON.stringify(q)} -> ${(await sheetText()).slice(0, 260)}`); };
    const wsave = async () => { const b = page.locator('button:has-text("Save")').last(); console.log('   WID save disabled?', await b.isDisabled().catch(() => '?')); await b.click({ timeout: 2000 }).catch(() => console.log('   WID save not clickable')); await page.waitForTimeout(1800); console.log('   after WID save:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 160)); };
    const pageWords = async (nm, label) => { await openItem(nm); const t = (await bodyText()).replace(/\s+/g, ' '); const i = t.search(/WHERE IT IS|Where it is/i); console.log(`   PAGE ${nm}: ${t.slice(Math.max(0, i), i + 300)}`); if (label) await shot(label); return t; };
    const newRows = async () => page.locator('.in-list button, .sheet button').filter({ hasText: /New place/ }).allInnerTexts().then(a => a.map(s => s.replace(/\s+/g, ' ').trim()));
    const srch = async (q, label) => { const i = page.locator('.in-list .wl-search input, .sheet .wl-search input').last(); await i.fill(''); await i.type(q, { delay: 10 }); await page.waitForTimeout(500); console.log(`SEARCH ${JSON.stringify(q)} -> NEW=${JSON.stringify(await newRows())} | ${(await sheetText()).slice(0, 200)}`); if (label) await shot(label); };
