    const dbl = async (sel, gap = 40) => { const b = await page.locator(sel).filter({ visible: true }).first().boundingBox().catch(() => null); if (!b) { console.log('   dbl: no', sel); return false; } const x = b.x + b.width / 2, y = b.y + b.height / 2; await page.mouse.click(x, y); await page.waitForTimeout(gap); await page.mouse.click(x, y); console.log(`   double-tapped ${sel} gap=${gap}`); return true; };
    const nItems = async (nm) => (await D()).filter(x => x.kind === 'item' && !x.deleted && (x.name || '').toLowerCase() === nm).length;
    const tapNewRow = async (gap) => { const b = page.locator('.in-list button').filter({ hasText: /New place/ }).first(); if (!(await b.count())) { console.log('   no New row'); return false; } if (gap !== undefined) { const bb = await b.boundingBox(); await page.mouse.click(bb.x + bb.width / 2, bb.y + bb.height / 2); await page.waitForTimeout(gap); await page.mouse.click(bb.x + bb.width / 2, bb.y + bb.height / 2).catch(() => {}); console.log('   double-tapped New row'); } else await b.click(); await page.waitForTimeout(700); return true; };
    console.log('COUNTS0', await cnt());
    console.log('\n######## S1 Log new item, New place from words, DOUBLE-TAP Save');
    await logStart('egg timer', 'real_spoon.jpg'); await setWords('in the cedar chest'); await openIn(); await tapNewRow(); console.log('   CAM', await camText());
    await dbl('.lc-k.sv', 30); await page.waitForTimeout(2500); await shot('s1-after'); console.log('   egg timers:', await nItems('egg timer')); await allPlaces(); await placeEdges(); console.log('COUNTS', await cnt(), errs());
    console.log('\n######## S2 DOUBLE-TAP Undo on the Home card');
    await dbl('button:has-text("Undo")', 30); await page.waitForTimeout(2000); await shot('s2-after'); console.log('   egg timers:', await nItems('egg timer')); await allPlaces(); await placeEdges(); console.log('COUNTS', await cnt(), errs());
    console.log('\n######## S3 Move it, DOUBLE-TAP the New place row, Save');
    await moveIt('wallet'); await setWords('in the bread bin'); await openIn(); await tapNewRow(30); console.log('   CAM', await camText(), '| in-list open?', await page.locator('.in-list').count()); await shot('s3-chip');
    if (await page.locator('.in-list').count()) await cancelChoose();
    await doSave(); await allPlaces(); await raw('wallet'); console.log('COUNTS', await cnt(), errs());
    console.log('\n######## S4 Move it pick + DOUBLE-TAP Save (Move)');
    await moveIt('reading glasses'); await openIn(); await pickIn('Linen closet'); await dbl('.lc-k.sv', 30); await page.waitForTimeout(2500); await raw('reading glasses'); await placeEdges(); await shot('s4-after');
    console.log('   item page undo count', await undoCount()); await dbl('button:has-text("Undo")', 30); await page.waitForTimeout(2000); await raw('reading glasses'); await placeEdges(); console.log('COUNTS', await cnt(), errs());
    console.log('\n######## S5 Save + Next: two items into a brand-new place');
    await logStart('hammer', 'tooldrawer.jpg'); await setWords('in the workbench cabinet'); await openIn(); await tapNewRow(); console.log('   CAM1', await camText());
    await hold('.lc-k.sv', 1200); await page.waitForTimeout(1500); console.log('   after hold CAM', await camText()); await shot('s5-next');
    AI = { name: 'chisel' }; await cam('scissors.jpg'); await tap('.lc-shutter', { wait: 2000 }); console.log('   CAM item2', await camText()); await shot('s5-item2');
    await hold('.lc-k.sv', 1200); await page.waitForTimeout(1500); console.log('   after hold2 CAM', await camText());
    AI = { name: 'mallet' }; await cam('book.jpg'); await tap('.lc-shutter', { wait: 2000 }); console.log('   CAM item3', await camText()); await doSave();
    await allPlaces(); await raw('hammer'); await raw('chisel'); await raw('mallet'); await placeEdges(); console.log('COUNTS', await cnt(), errs());
    console.log('-- S5 Undo on home card (last item) then is the place still there for hammer/chisel?'); await undo('S5 home'); await allPlaces(); await raw('mallet'); await raw('chisel'); await raw('hammer'); await placeEdges(); await shot('s5-undo');
    console.log('\n######## S6 Leave camera with the In list open (after tapping New place, list reopened)');
    const c0 = await cnt(); await logStart('stapler', 'scissors.jpg'); await setWords('in the sewing basket'); await openIn(); await tapNewRow(); await openIn(); console.log('   in-list open', await page.locator('.in-list').count()); await shot('s6-open');
    await home(); await page.waitForTimeout(800); console.log('   after home:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 160)); await allPlaces(); console.log('   staplers', await nItems('stapler'), 'COUNTS', c0, '->', await cnt());
    console.log('-- S6b In list open, browser Back'); await logStart('stapler', 'scissors.jpg'); await setWords('in the sewing basket'); await openIn(); await tapNewRow(); await openIn(); await page.goBack().catch(e => console.log('   goBack err', e.message.slice(0, 80))); await page.waitForTimeout(1200); console.log('   after back:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); await shot('s6b-back');
    if (await page.locator('.lc-k.sv').count()) { console.log('   still on camera:', await camText()); } await page.goto(`http://localhost:${PORT}/`); await page.waitForTimeout(1000); await allPlaces(); console.log('   staplers', await nItems('stapler'), 'COUNTS', await cnt());
    console.log('-- S6c In list open, Cancel camera behind it'); await logStart('stapler', 'scissors.jpg'); await openIn(); await page.locator('.lc-x').first().click({ timeout: 1500 }).then(() => console.log('   x clicked through sheet')).catch(() => console.log('   x not clickable under sheet')); await page.waitForTimeout(800); console.log('   ', (await bodyText()).replace(/\s+/g, ' ').slice(0, 160)); await home();
    console.log('   ', errs());
