    const nItems = async (nm) => (await D()).filter(x => x.kind === 'item' && !x.deleted && (x.name || '').toLowerCase() === nm).length;
    const R = async (fn, arg) => { await page.evaluate(fn, arg); await page.waitForTimeout(1200); };
    const remoteWords = async (nm, said) => { await R(([n, s]) => { const d = window.__rig.dump(); const it = d.find(x => x.kind === 'item' && !x.deleted && x.name.toLowerCase() === n); const t = Date.now(); const { id, ...rest } = it; window.__rig.seed([{ id, ...rest, updatedAt: t, history: [...(it.history || []), { at: t, w: 1, said: s, by: 'robert' }] }]); }, [nm, said]); console.log('   REMOTE words on', nm, JSON.stringify(said)); };
    const remoteMove = async (nm, place) => { await R(([n, p]) => { const d = window.__rig.dump(); const it = d.find(x => x.kind === 'item' && !x.deleted && x.name.toLowerCase() === n); const t = Date.now(); const edges = d.filter(x => x.kind === 'edge' && x.from === it.id && !x.until).map(e => ({ ...e, until: t })); const { id, ...rest } = it; window.__rig.seed([{ id, ...rest, location: p, lastSeenAt: t, updatedAt: t, history: [...(it.history || []), { location: p, at: t, w: 1, said: '', by: 'robert' }] }, ...edges, { id: 'eR' + t, kind: 'edge', rel: 'in', from: id, to: { t: 'place', name: p }, since: t, until: null, how: 'chosen', owner: 'margaret', by: 'robert', private: false, roles: {}, sharedWith: [] }]); }, [nm, place]); console.log('   REMOTE move', nm, '->', place); };
    const remoteNewIn = async (nm, boxName) => { await R(([n, b]) => { const d = window.__rig.dump(); const bx = d.find(x => x.kind === 'item' && !x.deleted && x.name.toLowerCase() === b); const t = Date.now(); window.__rig.seed([{ id: 'rn' + t, kind: 'item', owner: 'margaret', by: 'robert', private: false, roles: {}, sharedWith: [], name: n, location: bx.name, order: t, createdAt: t, updatedAt: t, lastSeenAt: t, photoCount: 0, history: [{ location: bx.name, at: t, by: 'robert' }] }, { id: 'eN' + t, kind: 'edge', rel: 'in', from: 'rn' + t, to: { t: 'item', id: bx.id, name: bx.name }, since: t, until: null, how: 'chosen', owner: 'margaret', by: 'robert', private: false, roles: {}, sharedWith: [] }]); }, [nm, boxName]); console.log('   REMOTE new', nm, 'in', boxName); };
    await grant();
    console.log('\n######## U5b Save + Next item1 -> another phone MOVES item1 -> camera Undo');
    await logStart('hammer', 'tooldrawer.jpg'); await openIn(); await pickIn('Garage shelf'); await hold('.lc-k.sv', 1200); await page.waitForTimeout(800); console.log('   CAM', await camText()); await shot('u5b-cam-before');
    await remoteMove('hammer', 'Linen closet'); const h1 = await raw('hammer'); const cu = page.locator('.lc button:has-text("Undo")').first(); console.log('   camera undo?', await cu.count());
    if (await cu.count()) { await cu.click(); await page.waitForTimeout(250); console.log('   after cam undo:', await camText()); await shot('u5b-cam-after'); } console.log('   hammers', await nItems('hammer')); await raw('hammer'); await placeEdges();
    await leaveCam(); await home();
    console.log('\n######## U5c Save + Next item1 -> another phone puts something IN item1? (n/a) -> words, shot fast');
    await logStart('hammer2', 'tooldrawer.jpg'); await openIn(); await pickIn('Garage shelf'); await hold('.lc-k.sv', 1200); await page.waitForTimeout(800); await remoteWords('hammer2', 'on the left hook'); await raw('hammer2'); const cu2 = page.locator('.lc button:has-text("Undo")').first(); if (await cu2.count()) { await cu2.click(); await page.waitForTimeout(250); console.log('   after cam undo:', await camText()); await shot('u5c-cam-after'); } console.log('   hammer2 count', await nItems('hammer2')); await leaveCam(); await home();
    console.log('\n######## BX1 Move wooden box (things inside); Robert adds words to the card; Undo box');
    const c0 = await raw('baseball card'); console.log('   chain', await chainOf('baseball card'));
    await moveIt('wooden box'); await openIn(); await pickIn('Pantry shelf'); await doSave(); console.log('   chain', await chainOf('baseball card'));
    await remoteWords('baseball card', 'in the plastic sleeve, top'); const c1 = await raw('baseball card');
    await undo('BX1 box'); await shot('bx1-after'); const c2 = await raw('baseball card'); await raw('wooden box'); console.log('   chain', await chainOf('baseball card'), '| card unchanged by box undo?', JSON.stringify(c1) === JSON.stringify(c2)); await pageWords('baseball card', 'bx1-card');
    console.log('\n######## BX2 Move wooden box; Robert moves the card OUT to Linen closet; Undo box');
    await moveIt('wooden box'); await openIn(); await pickIn('Garage shelf'); await doSave(); await remoteMove('baseball card', 'Linen closet'); const d1 = await raw('baseball card');
    await undo('BX2 box'); await shot('bx2-after'); const d2 = await raw('baseball card'); await raw('wooden box'); console.log('   chain card', await chainOf('baseball card'), '| wooden', await chainOf('wooden box'), '| card unchanged?', JSON.stringify(d1) === JSON.stringify(d2)); await placeEdges();
    console.log('\n######## BX3 Move wooden box; Robert puts a new thing into it; Undo box');
    await moveIt('wooden box'); await openIn(); await pickIn('Kitchen counter'); await doSave(); await remoteNewIn('ticket stub', 'wooden box'); await page.waitForTimeout(500); console.log('   box page:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 300));
    await undo('BX3 box'); await shot('bx3-after'); await raw('ticket stub'); await raw('wooden box'); console.log('   chain stub', await chainOf('ticket stub')); await placeEdges();
    console.log('\n######## BX4 Move wooden box; Robert moves the BOX itself; Undo');
    await moveIt('wooden box'); await openIn(); await pickIn('Craft nook'); await doSave(); await remoteMove('wooden box', 'Desk drawer'); const w1 = await raw('wooden box'); await undo('BX4'); const w2 = await raw('wooden box'); console.log('   box unchanged?', JSON.stringify(w1) === JSON.stringify(w2), '| chain', await chainOf('baseball card')); await shot('bx4-after');
    console.log('\n######## PI1 coffee can: Put it somewhere -> Craft nook -> Undo');
    const p0 = await raw('coffee can'); await openItem('coffee can'); await page.locator('button:has-text("Put it somewhere")').click(); await page.waitForTimeout(1000); await ui('put it somewhere'); await shot('pi1-sheet');
    if (await page.locator('.lc').count()) { console.log('   (opened the camera)'); await openIn(); await pickIn('Craft nook'); await doSave(); } else { const r = page.locator('.sheet .wl-row, .in-list .wl-row').filter({ has: page.locator('b:text-is("Craft nook")') }).first(); await r.click(); await page.waitForTimeout(1500); }
    console.log('   after put:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 300)); await shot('pi1-after'); const p1 = await raw('coffee can'); console.log('   undo', await undoCount());
    if (await undoCount()) { await undo('PI1'); const p2 = await raw('coffee can'); await shot('pi1-undone'); console.log('   back to before? loc', p0.location, '->', p2.location, 'needsPlace', p0.needsPlace, '->', p2.needsPlace, 'lastSeen', p0.lastSeenAt, '->', p2.lastSeenAt); await notPut(); }
    console.log('\n######## PI2 coffee can: Put it somewhere -> New place by name -> Robert puts something there -> Undo');
    await openItem('coffee can'); await page.locator('button:has-text("Put it somewhere")').click(); await page.waitForTimeout(1000);
    if (await page.locator('.lc').count()) { await setWords('in the bread bin'); await openIn(); const nb = page.locator('.in-list button').filter({ hasText: /New place/ }).first(); console.log('   new', await nb.allInnerTexts()); await nb.click(); await page.waitForTimeout(700); await doSave(); }
    else { const i = page.locator('.sheet input, .in-list input').last(); await i.fill('Bread bin'); await page.waitForTimeout(500); await page.locator('button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(1500); }
    await allPlaces(); await raw('coffee can'); await remoteMove('passport', 'Bread bin'); await raw('passport');
    if (await undoCount()) { await undo('PI2'); await shot('pi2-undone'); await allPlaces(); await raw('coffee can'); await raw('passport'); }
    console.log('   ', errs());
