    const placePage = async (nm) => { await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); const ok = await page.evaluate((n) => { const r = [...document.querySelectorAll('.loc-row')].find(b => b.innerText.split('\n')[0].trim().toLowerCase() === n.toLowerCase()); if (r) { r.scrollIntoView(); r.click(); return true; } return false; }, nm); if (!ok) { console.log('   NO PLACE ROW', nm); return false; } await page.waitForTimeout(900); return true; };
    const sheetNames = async () => page.evaluate(() => { const s = [...document.querySelectorAll('.sheet')].pop(); return s ? [...s.querySelectorAll('.wl-row b')].map(b => b.innerText.trim()) : []; });
    const pickR = async (nm) => { const l = page.locator('.sheet .wl-row').filter({ has: page.locator(`b:text-is("${nm}")`) }).first(); if (!(await l.count())) { console.log('   NOT OFFERED:', nm); return false; } await l.scrollIntoViewIfNeeded(); await l.click(); await page.waitForTimeout(1500); console.log('   picked', nm); return true; };
    const PP = async () => console.log('   PAGE:', (await bodyText()).replace(/\s+/g, ' ').replace(/^.*?Where this place is/, 'Where:').slice(0, 300));
    const dangling = async () => { const d = await D(); const live = d.filter(x => x.kind === 'place' && !x.deleted).map(p => p.name.toLowerCase()); const bad = d.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'place' && !live.includes((x.to.name || '').toLowerCase())).map(x => { const f = d.find(z => z.id === x.from); return `${f ? f.name : x.from}->${x.to.name}`; }); const badI = d.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'item' && !d.some(z => z.id === x.to.id && !z.deleted)).map(x => `${x.from}->item ${x.to.name}`); console.log('DANGLING (live edge to no live place/box):', [...bad, ...badI].join(' | ') || 'none'); };
    const R = async (fn, arg) => { await page.evaluate(fn, arg); await page.waitForTimeout(1200); };
    const remoteMove = async (nm, place) => { await R(([n, p]) => { const d = window.__rig.dump(); const it = d.find(x => x.kind === 'item' && !x.deleted && x.name.toLowerCase() === n); const t = Date.now(); const edges = d.filter(x => x.kind === 'edge' && x.from === it.id && !x.until).map(e => ({ ...e, until: t })); const { id, ...rest } = it; window.__rig.seed([{ id, ...rest, location: p, lastSeenAt: t, updatedAt: t, history: [...(it.history || []), { location: p, at: t, w: 1, said: '', by: 'robert' }] }, ...edges, { id: 'eR' + t, kind: 'edge', rel: 'in', from: id, to: { t: 'place', name: p }, since: t, until: null, how: 'chosen', owner: 'margaret', by: 'robert', private: false, roles: {}, sharedWith: [] }]); }, [nm, place]); console.log('   REMOTE move', nm, '->', place); };
    await grant(); await dangling();
    console.log('\n######## N1 Log item into a NEW place (home card), then MY OWN Move of another item into that place, then home Undo');
    await logStart('stapler', 'scissors.jpg'); await setWords('in the bread bin'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(700); await doSave(); await allPlaces(); console.log('   home undo', await undoCount());
    await moveIt('wallet'); await openIn(); await pickIn('Bread bin'); await doSave(); await raw('wallet'); await home(); console.log('   home undo after', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 120)); await shot('n1-home');
    if (await undoCount()) { await undo('N1'); await shot('n1-after'); await allPlaces(); await raw('stapler'); await raw('wallet'); await dangling(); }
    console.log('\n######## N2 Log item into a NEW place; Robert moves passport there; home Undo');
    await logStart('ruler', 'real_pencil.jpg'); await setWords('in the cedar chest'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(700); await doSave(); await allPlaces();
    await remoteMove('passport', 'Cedar chest'); await home(); console.log('   home undo', await undoCount()); await undo('N2'); await shot('n2-after'); await allPlaces(); await raw('ruler'); await raw('passport'); await dangling();
    await openItem('passport'); console.log('   PASSPORT PAGE:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 260)); await shot('n2-passport');
    console.log('\n######## N3 Move it into NEW place; Robert moves glasses there; page Undo');
    await moveIt('tin box'); await setWords('in the hat box'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(700); await doSave(); await allPlaces(); await remoteMove('reading glasses', 'Hat box'); await undo('N3'); await shot('n3-after'); await allPlaces(); await raw('tin box'); await raw('reading glasses'); await dangling();
    console.log('\n######## M1 Kitchen counter: row Move of spare batteries -> Pantry; Undo shown? ; then Remove KC; Undo after?');
    await moveIt('reading glasses').catch(() => {}); await leaveCam().catch(() => {});
    await placePage('Kitchen counter'); await PP(); await page.locator('.pl-move').first().click(); await page.waitForTimeout(800); await pickR('Pantry shelf'); await PP(); await shot('m1-rowmove'); console.log('   undo on place page', await undoCount()); await raw('spare batteries');
    const rmv = page.locator('button:has-text("Remove this place")'); console.log('   remove enabled?', !(await rmv.isDisabled().catch(() => true)));
    if (!(await rmv.isDisabled().catch(() => true))) { await rmv.click(); await page.waitForTimeout(800); await ui('remove confirm'); const y = page.locator('button').filter({ hasText: /^Remove/ }).filter({ visible: true }).last(); await y.click().catch(() => {}); await page.waitForTimeout(1200); console.log('   after remove:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); console.log('   undo visible now', await undoCount()); await shot('m1-removed'); if (await undoCount()) { await undo('M1 after remove'); await raw('spare batteries'); await dangling(); } }
    await allPlaces(); await dangling();
    console.log('\n######## M2 Desk drawer: Move all -> Craft nook; Undo?; Remove; Undo?');
    await placePage('Desk drawer'); await PP(); await page.locator('.pl-all').click(); await page.waitForTimeout(800); await pickR('Craft nook'); await PP(); await shot('m2-moveall'); console.log('   undo', await undoCount()); await raw('3d model of plant sensor'); await raw('passport');
    const rmv2 = page.locator('button:has-text("Remove this place")'); if (!(await rmv2.isDisabled().catch(() => true))) { await rmv2.click(); await page.waitForTimeout(800); const y = page.locator('button').filter({ hasText: /^Remove/ }).filter({ visible: true }).last(); await y.click().catch(() => {}); await page.waitForTimeout(1200); console.log('   after remove:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200), '| undo', await undoCount()); if (await undoCount()) { await undo('M2 after remove'); await dangling(); } }
    await allPlaces(); await dangling();
    console.log('\n######## M3 item page Move out of a place, then the place emptied + removed, then the item-page Undo');
    await moveIt('tote bin'); await openIn(); await pickIn('Linen closet'); await doSave(); console.log('   undo on tote page', await undoCount());
    const pg = await context.newPage().catch(() => null); console.log('   (single tab app; using Robert-style remote to empty Craft nook instead)');
    if (pg) await pg.close();
    const d0 = await D(); const inCN = d0.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'place' && x.to.name === 'Craft nook').map(x => (d0.find(z => z.id === x.from) || {}).name); console.log('   still in Craft nook:', inCN);
    for (const n of inCN) await remoteMove(n, 'Garage shelf');
    await R(() => { const d = window.__rig.dump(); const p = d.find(x => x.kind === 'place' && x.name === 'Craft nook'); const { id, ...rest } = p; window.__rig.seed([{ id, ...rest, deleted: true, updatedAt: Date.now() }]); });
    await allPlaces(); console.log('   tote page undo still?', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); await shot('m3-before-undo');
    if (await undoCount()) { await undo('M3'); await shot('m3-after'); await raw('tote bin'); await dangling(); await allPlaces(); }
    console.log('   ', errs());
