    const placePage = async (nm) => { await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); const ok = await page.evaluate((n) => { const r = [...document.querySelectorAll('.loc-row')].find(b => b.innerText.split('\n')[0].trim().toLowerCase() === n.toLowerCase()); if (r) { r.scrollIntoView(); r.click(); return true; } return false; }, nm); if (!ok) { console.log('   NO PLACE ROW', nm); return false; } await page.waitForTimeout(900); return true; };
    const sheetNames = async () => page.evaluate(() => { const s = [...document.querySelectorAll('.sheet')].pop(); return s ? [...s.querySelectorAll('.wl-row b')].map(b => b.innerText.trim()) : []; });
    const pickR = async (nm) => { const l = page.locator('.sheet .wl-row').filter({ has: page.locator(`b:text-is("${nm}")`) }).first(); if (!(await l.count())) { console.log('   NOT OFFERED:', nm); return false; } await l.scrollIntoViewIfNeeded(); await l.click(); await page.waitForTimeout(1500); console.log('   picked', nm); return true; };
    const PP = async () => console.log('   PAGE:', (await bodyText()).replace(/\s+/g, ' ').replace(/^.*?Where this place is/, 'Where:').slice(0, 300));
    const dangling = async () => { const d = await D(); const live = d.filter(x => x.kind === 'place' && !x.deleted).map(p => p.name.toLowerCase()); const bad = d.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'place' && !live.includes((x.to.name || '').toLowerCase())).map(x => { const f = d.find(z => z.id === x.from); return `${f ? f.name : x.from}->${x.to.name}`; }); const badI = d.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'item' && !d.some(z => z.id === x.to.id && !z.deleted)).map(x => `${x.from}->item ${x.to.name}`); console.log('DANGLING (live edge to no live place/box):', [...bad, ...badI].join(' | ') || 'none'); };
    const R = async (fn, arg) => { await page.evaluate(fn, arg); await page.waitForTimeout(1200); };
    const remoteMove = async (nm, place) => { await R(([n, p]) => { const d = window.__rig.dump(); const it = d.find(x => x.kind === 'item' && !x.deleted && x.name.toLowerCase() === n); const t = Date.now(); const edges = d.filter(x => x.kind === 'edge' && x.from === it.id && !x.until).map(e => ({ ...e, until: t })); const { id, ...rest } = it; window.__rig.seed([{ id, ...rest, location: p, lastSeenAt: t, updatedAt: t, history: [...(it.history || []), { location: p, at: t, w: 1, said: '', by: 'robert' }] }, ...edges, { id: 'eR' + t, kind: 'edge', rel: 'in', from: id, to: { t: 'place', name: p }, since: t, until: null, how: 'chosen', owner: 'margaret', by: 'robert', private: false, roles: {}, sharedWith: [] }]); }, [nm, place]); console.log('   REMOTE move', nm, '->', place); };
    await grant();
    console.log('\n######## M2 Craft nook: Move all -> Pantry shelf; Undo?; Remove; Undo?');
    await placePage('Craft nook'); await PP(); await page.locator('.pl-all').click(); await page.waitForTimeout(800); await pickR('Pantry shelf'); await PP(); await shot('m2-moveall'); console.log('   undo', await undoCount()); await raw('tote bin'); await raw('filing cabinet'); await placeEdges();
    const rmv2 = page.locator('button:has-text("Remove this place")'); console.log('   remove enabled', !(await rmv2.isDisabled().catch(() => true)));
    if (!(await rmv2.isDisabled().catch(() => true))) { await rmv2.click(); await page.waitForTimeout(800); const y = page.locator('button').filter({ hasText: /^Remove$/ }).filter({ visible: true }).last(); await y.click().catch(() => {}); await page.waitForTimeout(1200); console.log('   after remove:', (await bodyText()).replace(/\s+/g, ' ').slice(0, 200), '| undo', await undoCount()); await shot('m2-removed'); if (await undoCount()) { await undo('M2 after remove'); await dangling(); } }
    await allPlaces(); await dangling();
    console.log('\n######## M3 item-page Move of tote bin Pantry -> Linen closet; Robert moves filing cabinet away; Pantry removed remotely; tote page Undo');
    await moveIt('tote bin'); await openIn(); await pickIn('Linen closet'); await doSave(); console.log('   undo on tote page', await undoCount());
    await remoteMove('filing cabinet', 'Garage shelf');
    { const d0 = await D(); const inP = d0.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'place' && x.to.name === 'Pantry shelf').map(x => (d0.find(z => z.id === x.from) || {}).name); console.log('   still in Pantry shelf:', inP); for (const n of inP) await remoteMove(n, 'Garage shelf'); }
    await R(() => { const d = window.__rig.dump(); const p = d.find(x => x.kind === 'place' && x.name === 'Pantry shelf'); const { id, ...rest } = p; window.__rig.seed([{ id, ...rest, deleted: true, updatedAt: Date.now() }]); });
    await allPlaces(); console.log('   tote page undo still?', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 200)); await shot('m3-before-undo');
    if (await undoCount()) { await undo('M3'); await shot('m3-after'); await raw('tote bin'); await dangling(); await allPlaces(); }
    console.log('\n######## C1 camera Save + Next into a NEW place; Robert moves wallet there; camera Undo');
    await logStart('mallet', 'tooldrawer.jpg'); await setWords('in the sea chest'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(700); await hold('.lc-k.sv', 1200); await page.waitForTimeout(600); await allPlaces();
    await remoteMove('wallet', 'Sea chest'); const cu = page.locator('.lc button:has-text("Undo")').first(); console.log('   cam undo', await cu.count()); if (await cu.count()) { await cu.click(); await page.waitForTimeout(300); console.log('   after:', await camText()); await shot('c1-cam'); }
    await allPlaces(); await raw('mallet'); await raw('wallet'); await dangling(); await leaveCam();
    console.log('\n######## C2 Write it down into a NEW place (Attic); Robert moves passport there; Undo?');
    await wid('fan'); await widPick(); await srchW('Attic'); await page.locator('button').filter({ hasText: /New place: Attic/ }).first().click(); await page.waitForTimeout(700); await wsave(); await allPlaces(); await raw('fan'); await remoteMove('passport', 'Attic'); console.log('   undo', await undoCount(), (await bodyText()).replace(/\s+/g, ' ').slice(0, 160)); await shot('c2');
    if (await undoCount()) { await undo('C2'); await allPlaces(); await raw('fan'); await raw('passport'); await dangling(); }
    console.log('   ', errs());
