    const placePage = async (nm) => { await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); const ok = await page.evaluate((n) => { const r = [...document.querySelectorAll('.loc-row')].find(b => b.innerText.split('\n')[0].trim().toLowerCase() === n.toLowerCase()); if (r) { r.scrollIntoView(); r.click(); return true; } return false; }, nm); if (!ok) { console.log('   NO PLACE ROW', nm); return false; } await page.waitForTimeout(900); return true; };
    const sheetNames = async () => page.evaluate(() => { const s = [...document.querySelectorAll('.sheet')].pop(); return s ? [...s.querySelectorAll('.wl-row b')].map(b => b.innerText.trim()) : []; });
    const pickR = async (nm) => { const l = page.locator('.sheet .wl-row').filter({ has: page.locator(`b:text-is("${nm}")`) }).first(); if (!(await l.count())) { console.log('   NOT OFFERED:', nm); return false; } await l.scrollIntoViewIfNeeded(); await l.click(); await page.waitForTimeout(1500); console.log('   picked', nm); return true; };
    const PP = async () => console.log('   PAGE:', (await bodyText()).replace(/\s+/g, ' ').replace(/^.*?Where this place is/, 'Where:').slice(0, 300));
    const dangling = async () => { const d = await D(); const live = d.filter(x => x.kind === 'place' && !x.deleted).map(p => p.name.toLowerCase()); const bad = d.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'place' && !live.includes((x.to.name || '').toLowerCase())).map(x => { const f = d.find(z => z.id === x.from); return `${f ? f.name : x.from}->${x.to.name}`; }); const badI = d.filter(x => x.kind === 'edge' && !x.until && x.to.t === 'item' && !d.some(z => z.id === x.to.id && !z.deleted)).map(x => `${x.from}->item ${x.to.name}`); console.log('DANGLING (live edge to no live place/box):', [...bad, ...badI].join(' | ') || 'none'); };
    const R = async (fn, arg) => { await page.evaluate(fn, arg); await page.waitForTimeout(1200); };
    const remoteMove = async (nm, place) => { await R(([n, p]) => { const d = window.__rig.dump(); const it = d.find(x => x.kind === 'item' && !x.deleted && x.name.toLowerCase() === n); const t = Date.now(); const edges = d.filter(x => x.kind === 'edge' && x.from === it.id && !x.until).map(e => ({ ...e, until: t })); const { id, ...rest } = it; window.__rig.seed([{ id, ...rest, location: p, lastSeenAt: t, updatedAt: t, history: [...(it.history || []), { location: p, at: t, w: 1, said: '', by: 'robert' }] }, ...edges, { id: 'eR' + t, kind: 'edge', rel: 'in', from: id, to: { t: 'place', name: p }, since: t, until: null, how: 'chosen', owner: 'margaret', by: 'robert', private: false, roles: {}, sharedWith: [] }]); }, [nm, place]); console.log('   REMOTE move', nm, '->', place); };
    await grant();
    console.log('\n######## H1 same phone: wallet into Linen closet (page); re-log wallet from Home into Garage shelf (card Undo); remove Linen closet; Home Undo');
    await moveIt('wallet'); await openIn(); await pickIn('Linen closet'); await doSave(); await raw('wallet');
    await home(); await page.click(LOG); await page.waitForTimeout(900); AI = { name: 'wallet' }; SAME = { index: 1, sure: true }; await cam('wallet.jpg'); await tap('.lc-shutter', { wait: 2500 }); SAME = { index: -1, sure: false }; console.log('   CAM', await camText());
    if (await btn(/^Yes$/)) { console.log('   CAM after yes', await camText()); await openIn(); await pickIn('Garage shelf'); await doSave(); await raw('wallet'); console.log('   home undo', await undoCount()); await shot('h1-card');
      await placePage('Linen closet'); await PP(); const rmv = page.locator('button:has-text("Remove this place")'); console.log('   remove enabled', !(await rmv.isDisabled().catch(() => true)));
      if (!(await rmv.isDisabled().catch(() => true))) { await rmv.click(); await page.waitForTimeout(800); await page.locator('button').filter({ hasText: /^Remove$/ }).filter({ visible: true }).last().click(); await page.waitForTimeout(1200); }
      await allPlaces(); await home(); console.log('   home undo after remove', await undoCount()); await shot('h1-home-before-undo');
      if (await undoCount()) { await undo('H1'); await shot('h1-after'); await raw('wallet'); await dangling(); await allPlaces(); await pageWords('wallet', 'h1-wallet-page'); }
    } else await leaveCam();
    console.log('\n######## H2 consequences of a deleted new place: Move it -> new "Hat box"; Robert puts glasses there; Undo; what does she see');
    await moveIt('tin box'); await setWords('in the hat box'); await openIn(); await page.locator('.in-list button').filter({ hasText: /New place/ }).first().click(); await page.waitForTimeout(700); await doSave(); await remoteMove('reading glasses', 'Hat box'); await undo('H2'); await dangling();
    await pageWords('reading glasses', 'h2-glasses-page'); await home(); await page.click('.menu-btn'); await page.waitForTimeout(500); await page.click('.drawer-row:has-text("Places")'); await page.waitForTimeout(900); console.log('   PLACES LIST:', JSON.stringify(await page.locator('.loc-row').allInnerTexts())); await shot('h2-places');
    await moveIt('wallet'); await openIn(); console.log('   In list has Hat box?', /Hat box/.test(await inText())); await setWords('hat box'); await page.waitForTimeout(300); await cancelChoose().catch(() => {}); await openIn(); console.log('   words "hat box" ->', (await inText()).replace(/\n+/g, ' / ').slice(0, 200)); await cancelChoose(); await leaveCam();
    console.log('   ', errs());
